<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MaoX</RootNamespace>
    <AssemblyName>MaoXLauncher</AssemblyName>
    <Product>MaoX Launcher</Product>
    <ApplicationIcon>..\MaoX.UI\Assets\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaoX.UI\MaoX.UI.csproj" />
  </ItemGroup>

</Project>
